version: 2
updates:
  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: daily
    groups:
      devcontainers-dependencies:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
