[project]
name = "git-profiles"
version = "0.3.0"
description = "CLI tool to manage multiple Git configuration profiles"
authors = [
    { name = "Niklas Kaaf", email = "nkaaf@protonmail.com" }
]
maintainers = [
    { name = "Niklas Kaaf", email = "nkaaf@protonmail.com" }
]
readme = "README.md"
requires-python = ">=3.10,<3.15"
keywords = ["git", "cli", "profiles", "configuration", "developer", "tools"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Version Control",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Typing :: Typed"
]
license-files = [
    "LICENSE"
]

dependencies = [
    "filelock==3.32.2",
    "platformdirs==4.11.0",
    "pydantic==2.13.4",
    "typing-extensions==4.16.0",
]

[project.urls]
homepage = "https://github.com/nkaaf/git-profiles"
source = "https://github.com/nkaaf/git-profiles"
issues = "https://github.com/nkaaf/git-profiles/issues"

[project.scripts]
git-profiles = "git_profiles.__main__:main"

[dependency-groups]
build = [
    "uv-build==0.12.0",
]
dev = [
    "faker==40.36.0",
    "poethepoet==0.48.0",
    "pre-commit==4.6.1",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "ruff==0.16.1",
    "ty==0.0.65",
    { "include-group" = "build" }
]

[build-system]
requires = ["uv_build==0.12.0"]
build-backend = "uv_build"

[tool.uv]
package = true
add-bounds = "exact"

[tool.uv.build-backend]
package = true

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ICN001", "COM812"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "INP001", "S101", "PLR2004"]

[tool.pytest]
minversion = "9.0.0"
testpaths = ["tests"]
strict = true

[tool.coverage.run]
source = ["src"]

# https://coverage.readthedocs.io/en/7.15.0/excluding.html#advanced-exclusion
[tool.coverage.report]
exclude_also = [
    'def __repr__',
    'if self.debug:',
    'if settings.DEBUG',
    'raise AssertionError',
    'raise NotImplementedError',
    'if 0:',
    'if __name__ == .__main__.:',
    'if TYPE_CHECKING:',
    'class .*\bProtocol\):',
    '@(abc\.)?abstractmethod',
]

[tool.poe.executor]
type = "uv"

[tool.poe.tasks]
ty = "ty check"
ruff_check = "ruff check"
ruff_format = "ruff format"
pre-commit = "pre-commit run --all-files"
ruff = ["ruff_check", "ruff_format"]
lint = ["ruff", "ty"]
test = ["test-py310", "test-py311", "test-py312", "test-py313", "test-py314"]
test-target = ["test-py310"]

[tool.poe.tasks.test-py310]
cmd = "pytest --cov --cov-report=xml:coverage-3.10.xml"
executor = {isolated = true, python = "3.10"}

[tool.poe.tasks.test-py311]
cmd = "pytest --cov --cov-report=xml:coverage-3.11.xml"
executor = {isolated = true, python = "3.11"}

[tool.poe.tasks.test-py312]
cmd = "pytest --cov --cov-report=xml:coverage-3.12.xml"
executor = {isolated = true, python = "3.12"}

[tool.poe.tasks.test-py313]
cmd = "pytest --cov --cov-report=xml:coverage-3.13.xml"
executor = {isolated = true, python = "3.13"}

[tool.poe.tasks.test-py314]
cmd = "pytest --cov --cov-report=xml:coverage-3.14.xml"
executor = {isolated = true, python = "3.14"}
