name: "Audit"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: "Linting"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Install project dependencies
        run: |
          uv sync

      - name: Run linting
        run: |
          uv run poe lint

  testing:
    name: "Testing"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Install project dependencies
        run: |
          uv sync

      - name: Cache tox environments
        uses: actions/cache@v4.3.0
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('pyproject.toml', 'tox.ini') }}

      - name: Run tests
        run: |
          uv run poe test

  audit:
    name: "Audit"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Audit
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
        with:
          inputs: '.'
