name: "Audit"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: "Linting"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up Python
        uses: actions/setup-python@v6.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Install project dependencies
        run: |
          uv sync

      - name: Run linting
        run: |
          uv run poe lint

  testing:
    name: "Testing"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Set up Python
        uses: actions/setup-python@v6.1.0

      - name: Explicit install git
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: git

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Install project dependencies
        run: |
          uv sync

      - name: Cache tox environments
        uses: actions/cache@v5.0.1
        with:
          path: .tox
          key: ${{ runner.os }}-tox-${{ hashFiles('pyproject.toml', 'tox.ini') }}

      - name: Run tests
        run: |
          uv run poe test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  audit:
    name: "Audit"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Audit
        uses: pypa/gh-action-pip-audit@1220774d901786e6f652ae159f7b6bc8fea6d266 # v1.1.0
        with:
          inputs: '.'
