name: "Publish"

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Upload to TestPyPi'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: "Build Package"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install python
        uses: actions/setup-python@v6.0.0
        with:
          check-latest: 'true'
          cache: 'pip'

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          enable-cache: true
          save-cache: true
          restore-cache: true

      - name: Build package
        run: |
          uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist/

  publish:
    if: startsWith(github.ref, 'refs/tags') || (github.event_name == 'workflow_dispatch' && github.event.inputs.test == 'true')
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: dist
          path: dist

      - name: Upload package to PyPi
        if: github.event.inputs.test == 'false'
        env:
          name: pypi
          url: https://pypi.org/p/pyds-stubs
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          attestations: true

      - name: Upload package to TestPyPi
        if: github.event.inputs.test == 'true'
        env:
          name: testpypi
          url: https://testpypi.org/p/pyds-stubs
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true
